//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeApp.Resources.Components.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QRCodeApp.Components.Pages.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save QR Code as picture on the device.
        /// </summary>
        internal static string DownloadQRCode {
            get {
                return ResourceManager.GetString("DownloadQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter QR Code Entry Name To Save.
        /// </summary>
        internal static string EnterQRCodeName {
            get {
                return ResourceManager.GetString("EnterQRCodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR Code.
        /// </summary>
        internal static string GenerateQRCode {
            get {
                return ResourceManager.GetString("GenerateQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text that will be used to generate the QR Code..
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved QR codes..
        /// </summary>
        internal static string NoSavedQRCodes {
            get {
                return ResourceManager.GetString("NoSavedQRCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code Generator App.
        /// </summary>
        internal static string QRCodeGenerator {
            get {
                return ResourceManager.GetString("QRCodeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Saved QR Code Entry.
        /// </summary>
        internal static string Regenerate {
            get {
                return ResourceManager.GetString("Regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved QR Codes.
        /// </summary>
        internal static string SavedQRCodes {
            get {
                return ResourceManager.GetString("SavedQRCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save QR Code.
        /// </summary>
        internal static string SaveQRCode {
            get {
                return ResourceManager.GetString("SaveQRCode", resourceCulture);
            }
        }
    }
}
